CRITICAL - 2022-04-17 09:08:13 --> Undefined property: App\Controllers\Home::$load
#0 C:\xampp\htdocs\Start\app\Controllers\Home.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Home->index()
#2 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-17 09:11:03 --> Undefined property: App\Controllers\Home::$load
#0 C:\xampp\htdocs\Start\app\Controllers\Home.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Home->index()
#2 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-17 23:08:12 --> Class "App\Controllers\DokumenModel" not found
#0 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->index()
#1 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#2 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-17 23:12:15 --> Class "App\Controllers\DokumenModel" not found
#0 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->index()
#1 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#2 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-17 23:26:55 --> Undefined variable $berkas
#0 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 13)
#1 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->index()
#2 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#3 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2022-04-17 23:28:14 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-04-17 23:28:14 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\Start\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\Start\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\Start\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(13): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->index()
#6 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#7 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-04-17 23:32:42 --> Undefined variable $berkas
#0 C:\xampp\htdocs\Start\app\Views\viewdokumen.php(90): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 90)
#1 C:\xampp\htdocs\Start\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Start\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\Start\system\Common.php(1089): CodeIgniter\View\View->render('viewdokumen', Array, true)
#4 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(14): view('viewdokumen', Array)
#5 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->index()
#6 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#7 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-17 23:53:50 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-17 23:53:50 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\Start\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\Start\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Start\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Start\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Start\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(45): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->save()
#9 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#10 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-04-17 23:56:08 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-17 23:56:08 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\Start\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\Start\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Start\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Start\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Start\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(45): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->save()
#9 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#10 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-04-17 23:58:34 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-17 23:58:34 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\Start\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\Start\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\Start\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Start\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Start\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Start\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Start\app\Controllers\Dokumen.php(45): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Start\system\CodeIgniter.php(832): App\Controllers\Dokumen->save()
#9 C:\xampp\htdocs\Start\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dokumen))
#10 C:\xampp\htdocs\Start\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Start\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Start\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
